name: CI/CD

on:
  push:
    branches:
      - '22-pipeline'
  pull_request:
    types:
      - closed

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  

    - name: Install dependencies
      run: |
        npm install

    - name: Run unit tests
      run: |
        npm test || true
        
    - name: Code static analysis
      run: |
        npm install eslint-config-google --save-dev 
        npx eslint . --no-error-on-unmatched-pattern
      continue-on-error: true
    - name: Formatting
      run: |
        npm install prettier
        npx prettier --check "server/*.js" --write "server/app.js" "server/db_app.js" "server/db_sequalize.js" "server/index.js"

    - name: Prevent push on failure
      if: failure()
      run: exit 1

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push app
      uses: docker/build-push-action@v3   
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/oxygen-cs:latest
